#!/usr/bin/env bash

_exists() { command -v "$1" &>/dev/null; }

_exists zoxide && alias cd="z"
_exists bat && alias cat="bat"
_exists nvim && alias vim="nvim"
_exists btop && alias top="btop"
_exists less && alias more="less"
_exists paru && alias pacman="paru"
_exists fzf && alias pgr="fzf | more"
_exists exa &&
    alias ls="eza -h --icons=auto --color=auto --group-directories-first -A" ||
    alias ls="ls -h --color=auto --group-directories-first -A"

alias ip="ip -color=auto"
alias diff="diff --color=auto"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

alias dev="devault"
alias cget="curl -O -L"
alias s="tmux-sessionizer.sh"

paclean() { pacman -Rns $(pacman -Qtdq) && sudo pacman -Scc; }
alias pacmirror="reflector --verbose --latest 5 --age 6 --sort rate --save /etc/pacman.d/mirrorlist"
