#!/bin/sh
[ "${TERM:-none}" = "linux" ] && \
    printf '%b' '\e]P0191113
                 \e]P1ffb1c2
                 \e]P2b1d18a
                 \e]P3f5bd6f
                 \e]P4b8c4ff
                 \e]P5c9beff
                 \e]P689d0ed
                 \e]P7efdee0
                 \e]P8191113
                 \e]P9ff7e9a
                 \e]PA99c365
                 \e]PBf2a73f
                 \e]PC859aff
                 \e]PD9f8bff
                 \e]PE5dbee6
                 \e]PFefdee0
                 \ec'
