#!/bin/sh
[ "${TERM:-none}" = "linux" ] && \
    printf '%b' '\e]P0161217
                 \e]P1fbb0d8
                 \e]P291d5ad
                 \e]P3f5bd6f
                 \e]P4b8c4ff
                 \e]P5c9beff
                 \e]P689d0ed
                 \e]P7e9e0e7
                 \e]P8161217
                 \e]P9f97fc0
                 \e]PA6cc791
                 \e]PBf2a73f
                 \e]PC859aff
                 \e]PD9f8bff
                 \e]PE5dbee6
                 \e]PFe9e0e7
                 \ec'
