[colors.primary]
background = '#0e1514'
foreground = '#dde4e3'

[colors.cursor]
text = '#dde4e3'
cursor = '#bec9c8' 

[colors.vi_mode_cursor]
text = '#dde4e3'
cursor = '#80d5d3' 

[colors.search.matches]
foreground = '#3f4948' 
background = '#b2c8e8' 

[colors.search.focused_match]
foreground = '#3f4948' 
background = '#80d5d3' 

[colors.footer_bar]
foreground = '#3f4948' 
background = '#dde4e3' 

[colors.hints.start]
foreground = '#3f4948' 
background = '#b0cccb' 

[colors.hints.end]
foreground = '#3f4948' 
background = '#b0cccb' 

[colors.selection]
text = '#0e1514'
background = '#80d5d3'

[colors.normal]
black = '#0e1514' 
red = '#ffb4ab' 
green = '#80d5d3' 
yellow = '#006a69' 
blue = '#80d5d3' 
magenta = '#b2c8e8' 
cyan = '#b0cccb' 
white = '#dde4e3'

[colors.bright]
black = '#0e1514' 
red = '#fbb0d8'
green = '#91d5ad'
yellow = '#d5c871'
blue = '#99ccfa'
magenta = '#aac7ff'
cyan = '#80d4db'
white = '#dde4e3'

[colors.dim]
black = '#0e1514' 
red = '#f97fc0'
green = '#6cc791'
yellow = '#c9b94a'
blue = '#68b4f8'
magenta = '#77a5ff'
cyan = '#58c7d0'
white = '#bec9c8'
