[manager]
cwd = { fg = "#e4bdc2", bold=true}

hovered         = { fg = "#ffd9de", bg = "#713341" }
preview_hovered = { underline = true, bold=true }


[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#ffd9de", bg = "#713341" }

# Mode
mode_normal = { fg = "#551d2b",   bg = "#ffb1bf", bold = true }
mode_select = { fg = "#43292e", bg = "#e4bdc2", bold = true }
mode_unset  = { fg = "#462a08",  bg = "#ebbe90", bold = true }

[which]
separator       = "  "
mask            = { bg = "#261d1f" }
cand            = { fg = "#ffb1bf" }
desc            = { fg = "#e4bdc2" }
separator_style = { fg = "#ebbe90" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#e4bdc2" },

	# Videos
	{ mime = "video/*", fg = "#ebbe90" },
	{ mime = "audio/*", fg = "#ebbe90" },

	# Archives
	{ mime = "application/zip",             fg = "#ffb4ab" },
	{ mime = "application/gzip",            fg = "#ffb4ab" },
	{ mime = "application/x-tar",           fg = "#ffb4ab" },
	{ mime = "application/x-rar",           fg = "#ffb4ab" },
	{ mime = "application/x-bzip",          fg = "#ffb4ab" },
	{ mime = "application/x-bzip2",         fg = "#ffb4ab" },
	{ mime = "application/x-7z-compressed", fg = "#ffb4ab" },

	# Fallback
	{ name = "*", fg = "#ffb1bf", bold=true },
	{ name = "*/", fg = "#e4bdc2", bold=true }
]
