[manager]
cwd = { fg = "#dac3a0", bold=true}

hovered         = { fg = "#ffdea8", bg = "#5e4200" }
preview_hovered = { underline = true, bold=true }


[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#ffdea8", bg = "#5e4200" }

# Mode
mode_normal = { fg = "#422d00",   bg = "#eebf6d", bold = true }
mode_select = { fg = "#3c2e15", bg = "#dac3a0", bold = true }
mode_unset  = { fg = "#203619",  bg = "#b3cea6", bold = true }

[which]
separator       = "  "
mask            = { bg = "#241f17" }
cand            = { fg = "#eebf6d" }
desc            = { fg = "#dac3a0" }
separator_style = { fg = "#b3cea6" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#dac3a0" },

	# Videos
	{ mime = "video/*", fg = "#b3cea6" },
	{ mime = "audio/*", fg = "#b3cea6" },

	# Archives
	{ mime = "application/zip",             fg = "#ffb4ab" },
	{ mime = "application/gzip",            fg = "#ffb4ab" },
	{ mime = "application/x-tar",           fg = "#ffb4ab" },
	{ mime = "application/x-rar",           fg = "#ffb4ab" },
	{ mime = "application/x-bzip",          fg = "#ffb4ab" },
	{ mime = "application/x-bzip2",         fg = "#ffb4ab" },
	{ mime = "application/x-7z-compressed", fg = "#ffb4ab" },

	# Fallback
	{ name = "*", fg = "#eebf6d", bold=true },
	{ name = "*/", fg = "#dac3a0", bold=true }
]
