[manager]
cwd = { fg = "#d4c0d7", bold=true}

hovered         = { fg = "#f8d8ff", bg = "#5d386b" }
preview_hovered = { underline = true, bold=true }


[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#f8d8ff", bg = "#5d386b" }

# Mode
mode_normal = { fg = "#442253",   bg = "#e4b7f3", bold = true }
mode_select = { fg = "#392c3d", bg = "#d4c0d7", bold = true }
mode_unset  = { fg = "#4c2524",  bg = "#f5b7b4", bold = true }

[which]
separator       = "  "
mask            = { bg = "#231e23" }
cand            = { fg = "#e4b7f3" }
desc            = { fg = "#d4c0d7" }
separator_style = { fg = "#f5b7b4" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#d4c0d7" },

	# Videos
	{ mime = "video/*", fg = "#f5b7b4" },
	{ mime = "audio/*", fg = "#f5b7b4" },

	# Archives
	{ mime = "application/zip",             fg = "#ffb4ab" },
	{ mime = "application/gzip",            fg = "#ffb4ab" },
	{ mime = "application/x-tar",           fg = "#ffb4ab" },
	{ mime = "application/x-rar",           fg = "#ffb4ab" },
	{ mime = "application/x-bzip",          fg = "#ffb4ab" },
	{ mime = "application/x-bzip2",         fg = "#ffb4ab" },
	{ mime = "application/x-7z-compressed", fg = "#ffb4ab" },

	# Fallback
	{ name = "*", fg = "#e4b7f3", bold=true },
	{ name = "*/", fg = "#d4c0d7", bold=true }
]
